### ISSUE TITLE
How can i filter list 

### ISSUE THREAD

**Issue by Dushyant-123** [thejitesh/NestedExpandableRecyclerView#1]

**Comment by thejitesh** [comment]
For description i am working on it. 
Can you be more specific on u r Issue?
I mean what kind of filtering you need. An example could be useful .

**Comment by Dushyant-123** [comment]
Search all matched node from list and show on adapter

**Comment by thejitesh** [comment]
This functionality is specific to your Need, and i have not developed this Project considering this function.
There are Two options, Either u add this functionality and raise Merge request, or watch until i push this new functionality.

**Comment by Dushyant-123** [comment]
where you implement search filter in your project?
